version: 0.2

env:
  shell: bash
  variables:
    PROJECT: "enterprise-framework"
  # secrets-manager:
  #   key: secret-id:json-key:version-stage:version-id

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: latest
    commands:
      - python --version
      - pip install --no-input 'jira[cli]'
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.7.1/terraform_1.7.1_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
      - terraform --version
      - aws --version
  build:
    on-failure: ABORT
    commands:
      # - cd nonprod
      # - terraform init
      # - terraform apply -auto-approve -var="project_name=$PROJECT"
      # - cd ../module
      - cd module
      - python table_work.py $PROJECT
  # build:
  #   run-as: Linux-user-name
  #   on-failure: ABORT | CONTINUE
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
  #   # steps:
  # post_build:
  #   run-as: Linux-user-name
  #   on-failure: ABORT | CONTINUE
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
    # steps:
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
# artifacts:
#   files:
#     - location
#     - location
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   exclude-paths: excluded paths
#   enable-symlinks: no | yes
#   s3-prefix: prefix
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
